### ISSUE TITLE
Number of results inconsistent between views

### ISSUE THREAD

**Issue by lucaro** [vitrivr/vitrivr-ng#109] opened 2021-12-09 14:53 UTC
When segments are grouped by object, rather than shown independently, sometimes substantially fewer results are shown. I'm not sure if this is related to #108, the filtering mechanism, or something completely different.

**Comment by silvanheller** [comment] 2021-12-09 19:35
The limit is indeed different for objects and segments. Do you have an example where elements are actually missing? Because to me this sounds like a scrolling issue

**Comment by lucaro** [comment] 2021-12-10 07:33
It might very well be the same issue as #108, I couldn't say as I was never able to reproduce it consistently.

**Comment by silvanheller** [comment] 2022-04-01 07:55
I'll close this as non-reproducible

**Closed by silvanheller** 2022-04-01 07:55 UTC
Labels: bug, needs-information
